#!/usr/bin/env bash

PICTURE=/home/purple-mountain/nixos/dotfiles/i3/eva-wallpaper.png
# SCREENSHOT="scrot -z $PICTURE"

# BLUR="5x4"

# $SCREENSHOT
# convert $PICTURE -blur $BLUR $PICTURE
i3lock -i $PICTURE
# rm $PICTURE
