#!/usr/bin/env bash

# PICTURE=/home/purple-mountain/nixos/dotfiles/i3/eva-wallpaper.png
# # SCREENSHOT="scrot -z $PICTURE"
#
# # BLUR="5x4"
#
# # $SCREENSHOT
# # convert $PICTURE -blur $BLUR $PICTURE
#
# # i3lock -i $PICTURE

# i3lock

# rm $PICTURE

TMPBG=/tmp/screen_lock.png

# Take a screenshot
scrot $TMPBG

# Lock screen with the screenshot as background
i3lock -i $TMPBG

# Clean up the temporary file
rm $TMPBG
